### ISSUE TITLE
missing "dist" directory

### ISSUE THREAD

**Issue by robreiss** [bitovi/syn#117]
I am a bit confused on the proper way to import funcunit and syn into my project.
I am using es6 modules with webpack which is attempting to load funcunit via cjs build:
I installed funcunit with:
`npm install funcunit@3.1.0-pre.1`
when I perform my build I get an error:
`ERROR in ./~/funcunit/dist/cjs/funcunit.js
Module not found: Error: Cannot resolve module 'syn' in .../node_modules/funcunit/dist/cjs`
so i installed "syn"
`npm install syn`
but I still received the same error, I then saw that the git tag v0.2.0 had a "dist" folder so I installed directly from github using the v0.2.0 tag:
`npm install git://github.com/bitovi/syn.git#v0.2.0`
this worked, and now funcunit is working.
Should syn master branch have a dist folder?

Thanks for the great package, loving funcunit.

**Comment by jonnor** [comment]
npm packages in the 0.1.x series have this, but 0.2.x does not.

**Comment by vitalets** [comment]
hi @m-mujica

could you add dist to npm publish ?

**Comment by m-mujica** [comment]
hey @vitalets, sorry I'm out of the loop with this issue, but I'll take a look at the problem, I'll let you guys know when it's fixed.

**Comment by vitalets** [comment]
It would be great! thanks a lot!

**Comment by m-mujica** [comment]
I'm going to reopen this, since adding `!dist/` to `.npmignore` didn't work

**Comment by m-mujica** [comment]
ok guys, 0.2.2 fixes the problem with the dist folder, try that one and let me know if you find anything weird

<img width="189" alt="screen shot 2016-07-08 at 15 43 07" src="https://cloud.githubusercontent.com/assets/724877/16699557/d224f4d8-4522-11e6-9b65-3cc6c0156927.png">

**Comment by vitalets** [comment]
I can confirm that now everything ok! Thanks a lot!

**Comment by robreiss** [comment]
Confirmed. Its working for me now. Thank you.
