### ISSUE TITLE
dist folder is missing from 0.4.0 release

### ISSUE THREAD

**Issue by bergie** [bitovi/syn#125]
We just received a PR to update to latest Syn package (noflo/noflo-ui#677) that fails in CI. Looking at it, it appears that the package downloaded from NPM doesn't contain the `dist` folder.

**Comment by chasenlehara** [comment]
Sorry about that @bergie, we’ll get a fix out today.

**Comment by chasenlehara** [comment]
0.4.2 is out and has the `dist` folder. Thanks for your patience!
