### ISSUE TITLE
Add the “key” property to events

### ISSUE THREAD

**Issue by chasenlehara** [bitovi/syn#180]
Syn currently emits events with the [which](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) property, which has been deprecated in favor of the [key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) property.

Syn sets `which` here: https://github.com/bitovi/syn/blob/37814415f59a3e8b75770d5dd010263d8d63963a/src/key.js#L404-L409

**Comment by cherifGsoul** [comment]
https://github.com/bitovi/syn/blob/cb614a64bf7947b4fb86c5d45cbc38a94ae45efd/src/key.js#L743
`key` property is readonly, the created event in the line above will be without `key` property on firefox.
To fix this it seems the event should be created with [`KeyboardEvent` constructor](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent).

None of IE versions support this event.
