### ISSUE TITLE
Syn.click does not fire focus event

### ISSUE THREAD

**Issue by aristotelos** [bitovi/syn#71]
The event `focus` is not fired when using `Syn.click`. This should be the default behaviour because a user click will also trigger a `focus`.

Although the blog says: "A click is the following sequence of events followed by the event’s default actions:
- `mousedown`
- `focus` (Called only if the element was focusable, and mousedown’s default actions were not prevented)
- `mouseup`
- `click`"

this is not true. Notice the JavaScriptMVC documentation states: "Clicks an element by triggering a mousedown, mouseup, and a click event." (http://v3.javascriptmvc.com/docs.html#&who=Syn.prototype.click). This is indeed how it is implemented now, but a `focus` should be fired too.

**Comment by fresheneesz** [comment]
Seems like this is still the case 4 months later.

**Comment by justinbmeyer** [comment]
@aristotelos I'm confused by what you are reporting.  What isn't true?  You are calling Syn.click on a focus-able element and there is no focus event?  I'm certain this was working.  What browser are you using? cc @fresheneesz

**Comment by fresheneesz** [comment]
Here's a test:

```
<body>
    <input id='b'>
    <input id='c'>
</body>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="Syn.js"></script>

<script>

    $("#b").keydown(function(event) {
        console.log("keydown b")
    })
    $("#b").keyup(function(event) {
        console.log("keyup b")
    })
    $("#b").change(function(event) {
        console.log("change b")
    })
    $("#b")[0].addEventListener('onfocus', function(event) {
        console.log("FOCUS b")
    })
    $("#b").click(function(event) {
        console.log("click b")
    })


    $("#c")[0].addEventListener('onfocus', function(event) {
        console.log("FOCUS c")
    })
    $("#c").click(function(event) {
        console.log("click c")
    })

    syn.type($("#b")[0], "x", function() {
        syn.click($("#b")[0], function() {
            syn.click($("#c")[0])
        })
    })

</script>
```

In chrome I get (in the console): 

keydown b
keyup b
click b
click c

**Comment by fresheneesz** [comment]
Oops, lol, change that to `addEventListener('focus'` - I'm just getting all confused trying to figure out what's working properly and what isn't. NEVERMIND!

**Comment by fresheneesz** [comment]
syn.type doesn't fire focus tho. That's a problem right? There's no manual way to type in something without focusing on it right? @justinbmeyer

**Comment by kdillon** [comment]
Added tests for a bunch of focus event scenarios, so this should be locked-down now.

Scenarios now include: 

- click
- dblclick
- rightClick
- tab into (focus)
- tab out (blur)
- anti-tab into
- anti-tab out
- tab wrap (last focusable element on the page) into
- tab wrap out
- anti-tab wrap (first focusable element on the page)
- anti-tab wrap out

Confirmed that these are working on Firefox and Chrome. If there are any scenarios that you would like to see added to the list, please feel free to open a new issue or drop me a line in gitter. Or if you have any problems with these, let me know. Thanks!
