### ISSUE TITLE
NPM release?

### ISSUE THREAD

**Issue by fresheneesz** [bitovi/syn#75]
It'd be nice to have this on npm, for those of us that use that as our package manager.

**Comment by justinbmeyer** [comment]
I can do this if you want to help. Thanks!

**Comment by fresheneesz** [comment]
Since the name `syn` is taken, but the project looks abandoned, I'd contact the owner of the name (he's using it for the project https://github.com/leukhin/synergy ) and ask if you can use it. I've had good success getting people to hand over names for abandoned projects.

**Comment by justinbmeyer** [comment]
awesome!  Are you interested in becoming a contributor?  Syn and FuncUnit could use some attention.

**Comment by fresheneesz** [comment]
I am interested in contributing to Syn, not so much FuncUnit. I've actually written my own testing system @ https://github.com/fresheneesz/deadunit . But I was already beginning to put together functions for frontend functional testing, and I'm glad to see someone has a much more fleshed out system. I'd love to use Syn for testing https://github.com/Tixit/blocks.js and my company Tixit's frontend client. 

I'd be willing to spend some time improving Syn, espeically of course, where it would directly benefit my other work.

**Comment by justinbmeyer** [comment]
To be clear, FuncUnit is not a "testing" system.  It's just a wrapper to Syn's API to make it more friendly.  Similar to how FuncUnit can hook into mocha / jasmine / qunit, it can be made to hook into deadunit and provide the nicer API you are looking for.

**Comment by fresheneesz** [comment]
Ah I see, i was seeing FuncUnit as kind of an extension of Qunit. I'm a fan of modules that can be used either symbiotically or independently, over plugins built in a framework, which is why I'm more interested in Syn.  Its not something I'd want to build into deadunit, but rather use along side it.

**Comment by justinbmeyer** [comment]
> I'm a fan of modules that can be used either symbiotically or independently, over plugins built in a framework

I still think I'm not explaining what FuncUnit is right.  FuncUnit is a "modules that can be used either symbiotically or independently".  It's designed to work alongside any other testing harness.  You wouldn't have to build deadunit into it.  Instead, FuncUnit would just need a deadunit adaptor to know how to "stop" an async test.

FuncUnit could, in a few minutes, even be made to work totally independently of any test harness.  Currently, it breaks only because it is trying to "stop" an async test that it is in.  We could simply prevent the error if there is no test harness.

**Comment by justinbmeyer** [comment]
To be even more clear, I mean that with QUnit:

```
test("foo", function(){
  F("#abc").click();
  F("#def").type("hi")
})
```

FuncUnit is calling `QUnit.stop()` and `QUnit.start()` behind the scenes when it's finished running.  

With Jasmine:

```
it("foo", function(){
  F("#abc").click();
  F("#def").type("hi")
})
```

FuncUnit is setup to call `waitsFor` [here](https://github.com/bitovi/funcunit/blob/master/browser/adapters/jasmine.js#L2).

We could make FuncUnit work with something like Mocha even if it didn't have an adapter.  People would have to call stop/start themselves. Something like:

```
it("foo", function(done){
  F("#abc").click();
  F("#def").type("hi" , done)
})
```

**Comment by fresheneesz** [comment]
I think I get it, you use the specifics of those systems to make a cleaner, more synchrounous-looking API. But if you want to do something like this:

```
it("foo", function(done){
  F("#abc").click();
  assert.equal($("#abc").val(), "x", "X gon' give it to ya" );
})
```

how do you ensure that the assert is only run after the click (or whatever action) has been completed? Am I correct that most (or at least some) actions are asynchronous and wouldn't be completed at the point where the assert is run?

Deadunit  handles asynchronicity in a very different way from most unit testing systems - in that it doesn't provide any special asynchronous functions, but instead allows you to specify a number of assertions. If an asynchronous part didn't happen, you don't get enough assertions and the test fails. This also helps assert things inside catch statements with you standard try-catch instead of special "expectException" assertions. Any asynchrounous stuff in deadunit is whatever the user wants to use, nothing else is required.

**Comment by justinbmeyer** [comment]
You would:

```
it("foo", function(done){
  F("#abc").click(function(){
     assert.equal($("#abc").val(), "x", "X gon' give it to ya" );
  });
  F("#abc").type(function(){
     assert.equal($("#abc").val(), "x", "X gon' give it to ya" );
  });
})
```

no "callback hell" because you don't need to nest callbacks.

**Comment by fresheneesz** [comment]
Ah I see, that's pretty clever.
