### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by fresheneesz** [bitovi/syn#77]
The readme says all you need to do is run test/index.html but I get the following errors:

index.html:4 GET file:///omitted/syn/lib/qunit/qunit/qunit.css net::ERR_FILE_NOT_FOUND
index.html:12 GET file:///D:/omitted/syn/lib/qunit/qunit/qunit.js net::ERR_FILE_NOT_FOUND
index.html:14 Uncaught ReferenceError: QUnit is not defined
index.html:19 GET file:///D:/omitted/syn/lib/steal/steal.js net::ERR_FILE_NOT_FOUND
index.html:21 Uncaught ReferenceError: System is not defined

**Comment by kdillon** [comment]
Tests run fine for me on Chrome, Firefox, IE.

Could you please rerun these and re-open this issue with repro steps if it fails? Thanks!
