### ISSUE TITLE
Why have both `key` and `type`?

### ISSUE THREAD

**Issue by fresheneesz** [bitovi/syn#84]
Looks like `syn.type` basically  just loops over a string and calls `key` multiple times. Why not just expose `type`, since it seems to have a superset of the functionality `key` has?

**Comment by justinbmeyer** [comment]
Key can simulate key presses like the arrow keys that you couldn't put in a string.  And, there's no harm in supplying both.

**Comment by fresheneesz** [comment]
Can't you do stuff `syn.type(node, "typewhateveryouwant[up]keeptyping[up][up]moretyping")`? The only harm in supplying both is a slightly more complicated API.

**Comment by justinbmeyer** [comment]
Yes, you can do that for up, but not all keys for all keyboards (non english keyboards) have a character representation mapping in syn.

**Comment by fresheneesz** [comment]
I'm confused by that. How would one type something in with `syn.key` if it doesn't have a character representation mapping?
