### ISSUE TITLE
Offer: Can I write documentation?

### ISSUE THREAD

**Issue by fresheneesz** [bitovi/syn#87]
Can I write some documentation in the readme? Would you accept a pull request? Are these all the functions: `click`, `dblClick`,  `move`, `drag`, `key`, `type`, `rightClick`?

Anyways, I keep needing to refer back to the code to figure things out for this, and it'd be nice if could write some docs here that I could then refer to instead.

**Comment by justinbmeyer** [comment]
Absolutely. Let's plan on talking Monday. I'm giving a training until then.

**Comment by fresheneesz** [comment]
Sure, i can plan on talking monday, as long as it ends before 9pm

**Comment by fresheneesz** [comment]
When do you want to talk today? @justinbmeyer

**Comment by justinbmeyer** [comment]
@fresheneesz Sorry, it will have to be tomorrow.  I'm trying to get syn organized a bit better to make any contributions you want to do easier to manage.  I will hopefully have this done tomorrow.  Thanks for reminding me.

**Comment by fresheneesz** [comment]
Ok, it'll have to be before 7:30 if we do it tomorrow. Does that work for you - say 6:30 or 7?

**Comment by fresheneesz** [comment]
@justinbmeyer

**Comment by fresheneesz** [comment]
Turns out I can do it later, til about 8:30

**Comment by justinbmeyer** [comment]
@fresheneesz Sorry about the delay.  I finally finished all the work to get the project in a place where it will be easier for you to contribute.  @daffl will hopefully get CI working tomorrow.  But if you want to start adding docs, please do so here: https://github.com/bitovi/syn#use

**Comment by justinbmeyer** [comment]
@fresheneesz does that work for you?  I've given you write access to this repo.  Congrats! You are an official core team member!

**Comment by fresheneesz** [comment]
@justinbmeyer Thanks! Sure yeah that works for me. It may be a bit of time before I come back to this tho
