### ISSUE TITLE
ReferenceError: checkSupport is not defined

### ISSUE THREAD

**Issue by mistic100** [bitovi/syn#89]
I added the standalone version to my page and get this error.

I don't find any declaration of this function in the code.

Did I missed something ?

**Comment by thbar** [comment]
I get the same issue, trying to use syn in a Rails app. Did you manage to fix it so far?

**Comment by thbar** [comment]
@justinbmeyer do you know if a specific dependency must be added to have `checkSupport` defined? Thanks!

**Comment by abobwhite** [comment]
I am seeing the same issue. Totally unusable.

**Comment by justinbmeyer** [comment]
I'm not sure what's happening.  Something must be wrong with how the project is being exported.  I'll take a look.  Thanks!

**Comment by abobwhite** [comment]
This is now resolved in master,  but the latest version in npm does not have the fix...
