### ISSUE TITLE
npm test doesn't work OOTB

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/syn#99]
Simply cloning syn, running `npm install` and then `npm test` does not work

**Comment by matthewp** [comment]
What errors do you get?

**Comment by mickmcgrath13** [comment]
- [ ] missing grunt-contrib-uglify
- [ ] missing phantomjs
- [ ] incorrect reference to test file

**Comment by mickmcgrath13** [comment]
I'm about to push a branch

**Comment by mickmcgrath13** [comment]
PR: https://github.com/bitovi/syn/pull/100
